[program:redis]
command=/usr/bin/redis-server /etc/redis/redis.conf --daemonize no --save "" --appendonly no --logfile ""
priority=10
autostart=true
autorestart=true
startsecs=2
startretries=10
stopsignal=TERM
stopwaitsecs=10
stdout_logfile=/var/log/redis.out.log
stderr_logfile=/var/log/redis.err.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=1

[program:nginx]
command=/usr/local/bin/nginx-supervisor.sh
priority=20
autostart=true
autorestart=true
startsecs=2
startretries=10
stopsignal=QUIT
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/nginx.out.log
stderr_logfile=/var/log/nginx.err.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=1

[program:flask_app]
command=/usr/bin/python3 -B -m gunicorn -w 5 -b 0.0.0.0:5000 -k gevent -t 60 app:app
directory=/app
priority=30
autostart=true
autorestart=true
startsecs=2
startretries=10
stopsignal=TERM
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/flask_app.err.log
stdout_logfile=/var/log/flask_app.out.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=1
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1

[program:queue_processor]
command=/usr/bin/python3 -B /app/queue_processor.py
directory=/app
priority=30
autostart=true
autorestart=true
startsecs=2
startretries=10
stopsignal=TERM
stopwaitsecs=10
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/queue_processor.err.log
stdout_logfile=/var/log/queue_processor.out.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=1
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1
